# default prompt for all python based code benchmark evaluations on system prompt.
# used by models which are trained with this prompt.

system: |-
  You are a helpful and harmless assistant.\n\nYou are not allowed to use any tools.

user: |-
  {problem}\n\nPlease place your final answer inside \boxed{{}}.